vim9script

# BEGIN VIM-PLUG BOOTSTRAP

# Install vim-plug if not found
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

# Run PlugInstall if there are missing plugins
autocmd VimEnter * if len(filter(values(g:plugs), '!isdirectory(v:val.dir)'))
  \| PlugInstall --sync | source $MYVIMRC
\| endif

# END VIM-PLUG

# BEGIN GENERAL OPTIONS

# settings to get colors working
if !has('gui_running')
  set t_Co=256
endif

# it's not me, it's you
set nocompatible

# space as leader
g:mapleader = " "

# better than off
syntax on

set backspace=indent,eol,start
set tabstop=4             
set shiftwidth=4
set expandtab
set scrolloff=5
set laststatus=2
set number
set relativenumber
set hlsearch
set incsearch

set showcmd
set showmatch
set ignorecase
set hidden
set nohls
set splitright
set splitbelow
set termguicolors
set numberwidth=4
set autoindent

g:guifont = "Iosevka Nerd Font:h14"
set sidescrolloff=8
set clipboard="unnamedplus"
set cmdheight=1
set timeoutlen=1000
set nowritebackup
set fileencoding="utf-8"
set pumheight=10
set cmdheight=1

g:cindent = true
set conceallevel=0
set signcolumn=yes
set nowritebackup
set shiftround
set smartindent
## END GENERAL OPTIONS

# BEGIN KEYMAPS
# Normal mode keymaps
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l
nnoremap <S-l> <cmd>:bnext<cr>
nnoremap <S-h> <cmd>:bprevious<cr>
nnoremap <C-d> <C-d>zz
nnoremap <C-u> <C-u>zz

# Insert mode keymaps
inoremap jk <Esc>

# Visual mode keymaps
vnoremap J :m '>+1<CR>gv=gv
vnoremap K :m '<-2<CR>gv=gv
# END KEYMAPS

# BEGIN PLUGINS
call plug#begin()
# 	Plug 'catppuccin/vim', { 'as': 'catppuccin' } # Catppuccin Theme
    Plug 'jiangmiao/auto-pairs' #  For pairing brackets and quotes
    Plug 'mbbill/undotree' # for undoing changes visually
#   Plug 'christoomey/vim-tmux-navigator' 
    Plug 'bluz71/vim-moonfly-colors'
call plug#end()

# END PLUGINS

# BEGIN NETRW CONFIGURATION

g:netrw_banner = 0
g:netrw_altv = 1
g:netrw_liststyle = 3

# END NETRW CONFIGURATION
colorscheme moonfly

nnoremap <leader>f <cmd>:Ex<cr>
nnoremap <leader>u <cmd>:UndotreeToggle<cr>
# g:NERDTreeWinPos = right ***remember to replace quotes around value

# open held in vertical split on first open
autocmd Filetype help :wincmd L

# ROLLING MY OWN STATUSLINE

set statusline=
set statusline+=%.40F
set statusline+=\ 
set statusline+=%m
set statusline+=%=
set statusline+=%{'ln:'}\ 
set statusline+=%l\  
set statusline+=%{'of'}\ 
set statusline+=%L
set statusline+=\ \|
set statusline+=\ 
set statusline+=%{'col:'}\ 
set statusline+=%-3c

